<?php

use Application\Form\KleoForm;

$formulario = $this->formulario;
$formulario->prepare();

$formulario->setAttribute(KleoForm::stringAction, 'cadastroAnuncioFinalizar');
echo $this->form()->openTag($formulario);
echo $this->formHidden($formulario->get(KleoForm::inputCSRF));
echo $this->formHidden($formulario->get(KleoForm::inputId));
?>
<?php echo $this->cabecalhoPagina('Cadastro de Anuncio'); ?>   
<div class="content animate-panel">
  <div class="row">
    <div class="col-md-12">     
      <div class="hpanel">
        <div class="panel-body">
          <div class="text-center m-b-md" id="wizardControl">
            <a class="btn btn-info" href="#step1" data-toggle="tab">Passo 1 - Dados</a>
            <a class="btn btn-default" href="#step2" data-toggle="tab">Passo 2 - Fotos</a>
            <a class="btn btn-default" href="#step3" data-toggle="tab">Passo 3 - Aprovação</a>
          </div>
          <div class="tab-content">
            <div id="step1" class="p-m tab-pane active">
              <div class="row">
                <?php
                echo $this->inputFormulario(KleoForm::traducaoTitulo, $formulario->get(KleoForm::inputTitulo), 6);
                echo $this->inputFormulario(KleoForm::traducaoPreco, $formulario->get(KleoForm::inputPreco), 6);
                echo $this->inputFormulario(KleoForm::traducaoDescricao, $formulario->get(KleoForm::inputDescricao));
                ?>                
              </div>
              <div class="text-right m-t-xs">                
                <button style="margin-left:10px; padding: 10px;" type="button" class="btn btn-info pull-right ml10 next">Próximo</button>
                <?php echo $this->botao('Voltar', $this->funcaoOnClick('mudarPaginaComLoader("/cadastroAnuncios")'), 2); ?>
              </div>
            </div>
            <div id="step2" class="p-m tab-pane">
              <div class="row"> 
                <div class="form-group col-lg-3">
                  <div class='alert alert-danger' style='display:block;' id='message'></div>
                  <div id="image_preview">
                    <img id="previewing" src="" />
                  </div>
                  <?php
                  echo $this->inputFormulario(KleoForm::traducaoFotoPrincipal, $formulario->get(KleoForm::inputFoto1, 3));
                  ?>
                </div>
                <div class="form-group col-lg-9">
                  <div class="form-group col-lg-6">
                    <?php
                    echo $this->inputFormulario(KleoForm::traducaoFotoPrincipal, $formulario->get(KleoForm::inputFoto2));
                    ?>
                  </div>
                  <div class="form-group col-lg-6">
                    <?php
                    echo $this->inputFormulario(KleoForm::traducaoFotoPrincipal, $formulario->get(KleoForm::inputFoto3));
                    ?>
                  </div>
                </div>
                <div class="form-group col-offset-lg-3 col-lg-9">
                  <div class="form-group col-lg-6">
                    <?php
                    echo $this->inputFormulario(KleoForm::traducaoFotoPrincipal, $formulario->get(KleoForm::inputFoto4));
                    ?>
                  </div>
                  <div class="form-group col-lg-6">
                    <?php
                    echo $this->inputFormulario(KleoForm::traducaoFotoPrincipal, $formulario->get(KleoForm::inputFoto5));
                    ?>
                  </div>
                </div>
              </div>
              <div class="text-right m-t-xs">
                <button style="margin-left:10px; padding: 10px;" type="button" class="btn btn-info pull-right ml10 next">Próximo</button>
                <button style="margin-left:10px; padding: 10px;" type="button" class="btn btn-default pull-right ml10 prev">Anterior</button>                
              </div>
            </div>
            <div id="step3" class="tab-pane">
              <div class="row text-center m-t-lg m-b-lg">
                <div class="col-lg-12">
                  <i class="pe-7s-check fa-5x text-muted"></i>
                  <p class="small m-t-md">
                    <strong>There are many</strong> variations of passages of Lorem Ipsum available, but the majority have suffered
                  </p>
                </div>
                <div class="checkbox col-lg-12">
                  <input type="checkbox" class="i-checks approveCheck" name="approve">
                  Eu concordo com os termos
                </div>
              </div>
              <div class="text-right m-t-xs">
                <?php echo $this->botao('Cadastrar', $this->funcaoOnClickSubmeterFormulario()); ?>
                <button style="margin-left:10px; padding: 10px;" type="button" class="btn btn-default pull-right ml10 prev">Anterior</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<?php
echo $this->form()->closeTag();