
<!-- Main Wrapper -->
<div id="wrapper">
  <div class="content transition animate-panel fadeIn">
    <div class="row">
      <div class="col-lg-12">
        <div class="hpanel">
          <div class="panel-heading">
            <div class="panel-tools">
              <a class="showhide"><i class="fa fa-chevron-up"></i></a>
            </div>
            Listagem de Empresas
          </div>
          <div class="panel-body">

            <table id="tabelaEmpresasParaAnalise" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <th>Data</th>
                  <th>Nome</th>
                  <th>Contato</th>
                  <th>CNPJ</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <?php
                foreach($this->empresas as $empresa){

                  echo '<tr>';
                  echo '<td>'.$empresa->getData_criacao(). '</td>';
                  echo '<td>'.$empresa->getNome().'</td>';
                  echo '<td>'.$empresa->getTelefone().'</td>';
                  echo '<td>'.$empresa->getCNPJ().'</td>';
                  echo '<td>';
                  echo '<select class="form-control" onchange="mudarSituacao";>';

                  foreach($this->situacoes as $situacao){
                    $selected = '';
                    if($empresa->getEmpresaSituacaoAtivo()->getSituacao()->getId() === $situacao->GetId()){
                      $selected = 'selected'; 
                    }
                    echo   '<option '.$selected.'>'.$situacao->getNome().'</option>';
                  }

                  echo '</select>';                                            
                  echo '</td>';
                  echo '</tr>';
                }
                ?>                                
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  window.onload = initPage;

  function initPage() {
    $('#tabelaEmpresasParaAnalise').dataTable();
  }
</script>