<?php

use Application\Form\KleoForm;

$formulario = $this->formulario;
$formulario->prepare();

$formulario->setAttribute(KleoForm::stringAction, 'cadastroEmpresaFinalizar');
echo $this->form()->openTag($formulario);
echo $this->formHidden($formulario->get(KleoForm::inputCSRF));
echo $this->formHidden($formulario->get(KleoForm::inputId));
?>
<div class="register-container">
  <div class="row">
    <div class="col-md-12">
      <div class="text-center m-b-md">
        <h3>Cadastrar Matriz ou Filial</h3>
      </div>
      <div class="hpanel">
        <div class="panel-body">
          <?php
          echo $this->inputFormulario(KleoForm::traducaoNome, $formulario->get(KleoForm::inputNome));
          echo $this->inputFormulario(KleoForm::traducaoDDD, $formulario->get(KleoForm::inputDDD), 3);
          echo $this->inputFormulario(KleoForm::traducaoTelefone, $formulario->get(KleoForm::inputTelefone), 9);
          echo $this->inputFormulario(KleoForm::traducaoCNPJ, $formulario->get(KleoForm::inputCNPJ));
          echo $this->botao('Cadastrar', $this->funcaoOnClickSubmeterFormulario());
          ?>
        </div>
      </div>
    </div>
  </div>
</div>

<?php
echo $this->form()->closeTag();