<?php echo $this->cabecalhoPagina('Listagem de Lojas', $this->botao('Cadastrar', $this->funcaoOnClick('kleo("cadastroLoja", 0);'))); ?> 
<div class="content transition animate-panel fadeIn">
  <div class="row">
    <div class="col-lg-12">
      <div class="hpanel">         
        <div class="panel-body">
          <table id="tabelaEmpresasParaAnalise" class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th>Data</th>
                <th>Contato</th>
                <th>CNPJ</th>
                <th>Shopping</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              <?php
              $tipoPrimeiroContato = 1;
              foreach($this->lojas as $loja){
                echo '<tr>';
                echo '<td>'.$loja->getData_criacao(). '</td>';
                echo '<td>'.$loja->getTelefone().'</td>';
                echo '<td>'.$loja->getCNPJ().'</td>';
                echo '<td>'.$loja->getShopping()->getNome().'</td>';
                echo '<td>';
                echo $loja->getLojaSituacaoAtivo()->getSituacao()->getNome();
                if($loja->getLojaSituacaoAtivo()->getSituacao()->getId() === $tipoPrimeiroContato){                  
                  echo $this->botao('Alterar', $this->funcaoOnClick('kleo("cadastroLojaSituacao", '.$loja->getId().');'));
                }
                echo '</td>';
                echo '</tr>';
              }
              ?>                                
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  window.onload = initPage;

  function initPage() {
    $('#tabelaEmpresasParaAnalise').dataTable();
  }
</script>