
<!-- Main Wrapper -->
<div id="wrapper">
  <div class="content transition animate-panel fadeIn">
    <div class="row">
      <div class="col-lg-12">
        <div class="hpanel">
          <div class="panel-heading">
            <div class="panel-tools">
              <a class="showhide"><i class="fa fa-chevron-up"></i></a>
            </div>
            Listagem de Responsaveis
          </div>
          <div class="panel-body">

            <table id="tabelaEmpresasParaAnalise" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <th class="hidden-xs">Data</th>
                  <th>Nome Fantasia</th>
                  <th class="hidden-xs">Responsavel</th>
                  <th class="hidden-xs">Contato</th>
                  <th>Situação</th>
                </tr>
              </thead>
              <tbody>
                <?php
                foreach($this->responsaveis as $responsavel){

                  echo '<tr>';
                  echo '<td class="hidden-xs">'.$responsavel->getData_criacao(). '</td>';
                  echo '<td>'.$responsavel->getNomeFantasia().'</td>';
                  echo '<td class="hidden-xs">'.$responsavel->getNome().'</td>';
                  echo '<td class="hidden-xs">'.$responsavel->getTelefone().'</td>';
                  echo '<td>'.$responsavel->getResponsavelSituacaoAtivo()->getSituacao()->getNome();
                  if($responsavel->getResponsavelSituacaoAtivo()->getSituacao()->getId() === 1
                    || $responsavel->getResponsavelSituacaoAtivo()->getSituacao()->getId() === 3){
                    echo $this->botao('Alterar', $this->funcaoOnClick('kleo("cadastroResponsavelSituacao", '.$responsavel->getId().');'));
                  }
                  echo '</td>';
                  echo '</tr>';
                }
                ?>                                
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  window.onload = initPage;

  function initPage() {
    $('#tabelaEmpresasParaAnalise').dataTable();
  }
</script>