<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix signUp">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading"><h3>Senha Cadastrada com sucesso!</h3></div>
          <div class="panel-body text-center">
            <p><a href='/login' style="color:blue">Clique aqui para acessar</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>