
<!-- Main Wrapper -->
<div id="wrapper">
  <div class="content transition animate-panel fadeIn">
    <div class="row">
      <div class="col-lg-12">
        <div class="hpanel">
          <div class="panel-heading">
            <div class="panel-tools">
              <a class="showhide"><i class="fa fa-chevron-up"></i></a>
            </div>
            Listagem de Shoppings
          </div>
          <div class="panel-body">

            <table id="tabelaShoppingsParaAnalise" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <th>Data</th>
                  <th>Nome</th>
                </tr>
              </thead>
              <tbody>
                <?php
                foreach($this->shoppings as $shopping){
                  echo '<tr>';
                  echo '<td>'.$shopping->getData_criacao(). '</td>';
                  echo '<td>'.$shopping->getNome().'</td>';
                  echo '</tr>';
                }
                ?>                                
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  window.onload = initPage;

  function initPage() {
    $('#tabelaShoppingsParaAnalise').dataTable();
  }
</script>