<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Responsavel extends \Application\Model\Entity\Responsavel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inputFilter', 'inputFilterCadastrarResponsavel', 'inputFilterAtualizarResponsavel', 'responsavelSituacao', 'nome', 'telefone', 'email', 'cpf', 'data_nascimento', 'nome_fantasia', 'razao_social', 'cnpj', 'telefone_empresa', 'email_empresa', 'numero_lojas', 'token', 'upload_cpf', 'upload_contrato_social', 'id', 'data_criacao', 'hora_criacao', 'data_inativacao', 'hora_inativacao');
        }

        return array('__isInitialized__', 'inputFilter', 'inputFilterCadastrarResponsavel', 'inputFilterAtualizarResponsavel', 'responsavelSituacao', 'nome', 'telefone', 'email', 'cpf', 'data_nascimento', 'nome_fantasia', 'razao_social', 'cnpj', 'telefone_empresa', 'email_empresa', 'numero_lojas', 'token', 'upload_cpf', 'upload_contrato_social', 'id', 'data_criacao', 'hora_criacao', 'data_inativacao', 'hora_inativacao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Responsavel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getResponsavelSituacaoAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsavelSituacaoAtivo', array());

        return parent::getResponsavelSituacaoAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefone($telefone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefone', array($telefone));

        return parent::setTelefone($telefone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefone', array());

        return parent::getTelefone();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setCPF($cpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCPF', array($cpf));

        return parent::setCPF($cpf);
    }

    /**
     * {@inheritDoc}
     */
    public function getCPF()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCPF', array());

        return parent::getCPF();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataNascimento($dataNascimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataNascimento', array($dataNascimento));

        return parent::setDataNascimento($dataNascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataNascimento', array());

        return parent::getDataNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeFantasia($nomeFantasia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeFantasia', array($nomeFantasia));

        return parent::setNomeFantasia($nomeFantasia);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeFantasia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeFantasia', array());

        return parent::getNomeFantasia();
    }

    /**
     * {@inheritDoc}
     */
    public function getRazaoSocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRazaoSocial', array());

        return parent::getRazaoSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setRazaoSocial($razaoSocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRazaoSocial', array($razaoSocial));

        return parent::setRazaoSocial($razaoSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function setCnpj($cnpj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCnpj', array($cnpj));

        return parent::setCnpj($cnpj);
    }

    /**
     * {@inheritDoc}
     */
    public function getCnpj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCnpj', array());

        return parent::getCnpj();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefoneEmpresa($telefoneEmpresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefoneEmpresa', array($telefoneEmpresa));

        return parent::setTelefoneEmpresa($telefoneEmpresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefoneEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefoneEmpresa', array());

        return parent::getTelefoneEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailEmpresa($emailEmpresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailEmpresa', array($emailEmpresa));

        return parent::setEmailEmpresa($emailEmpresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailEmpresa', array());

        return parent::getEmailEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroLojas($numeroLojas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroLojas', array($numeroLojas));

        return parent::setNumeroLojas($numeroLojas);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroLojas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroLojas', array());

        return parent::getNumeroLojas();
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsavelSituacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsavelSituacao', array());

        return parent::getResponsavelSituacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsavelSituacao($responsavelSituacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsavelSituacao', array($responsavelSituacao));

        return parent::setResponsavelSituacao($responsavelSituacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', array());

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', array($token));

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadCPF()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadCPF', array());

        return parent::getUploadCPF();
    }

    /**
     * {@inheritDoc}
     */
    public function setUploadCPF($upload_cpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUploadCPF', array($upload_cpf));

        return parent::setUploadCPF($upload_cpf);
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadContratoSocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadContratoSocial', array());

        return parent::getUploadContratoSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setUploadContratoSocial($uploadContratoSocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUploadContratoSocial', array($uploadContratoSocial));

        return parent::setUploadContratoSocial($uploadContratoSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeArray($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', array($data));

        return parent::exchangeArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilterCadastrarResponsavel($validarRepetirEmail = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilterCadastrarResponsavel', array($validarRepetirEmail));

        return parent::getInputFilterCadastrarResponsavel($validarRepetirEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilterAtualizarResponsavel($validarRepetirEmail = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilterAtualizarResponsavel', array($validarRepetirEmail));

        return parent::getInputFilterAtualizarResponsavel($validarRepetirEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEHoraDeCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEHoraDeCriacao', array());

        return parent::setDataEHoraDeCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function verificarSeEstaAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'verificarSeEstaAtivo', array());

        return parent::verificarSeEstaAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEHoraDeInativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEHoraDeInativacao', array());

        return parent::setDataEHoraDeInativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function gerarToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gerarToken', array());

        return parent::gerarToken();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacao', array());

        return parent::getData_criacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getHora_criacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora_criacao', array());

        return parent::getHora_criacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacao', array());

        return parent::getData_inativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getHora_inativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora_inativacao', array());

        return parent::getHora_inativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_criacao($data_criacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_criacao', array($data_criacao));

        return parent::setData_criacao($data_criacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setHora_criacao($hora_criacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora_criacao', array($hora_criacao));

        return parent::setHora_criacao($hora_criacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_inativacao($data_inativacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_inativacao', array($data_inativacao));

        return parent::setData_inativacao($data_inativacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setHora_inativacao($hora_inativacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora_inativacao', array($hora_inativacao));

        return parent::setHora_inativacao($hora_inativacao);
    }

}
