<?php
/**
 * Caminho module/${nomeModulo}/view/${nomeModulo}/${nomeTabela}/list.phtml
 */
$title = '${nomeNoPlural}';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
        <li>
            <a href="<?php echo $this->url('${nomeTabela}', array('action' => 'create')); ?>">  
                <?php echo $this->translate('Criar novo registro') ?>
            </a>
        </li>        
    </ul>
</div>
<br />
<?php
if ($${nomeNoPlural}) {
    ?>
    <table class="table">
        <tr>
            ${tbCabecalho}
            <th>Ações</th>
        </tr>
        <?php
        if ($${nomeNoPlural}) {
            foreach ($${nomeNoPlural} as $${nomeVariavel}) {
                ?>
                <tr>
                    ${tbLinhas}
                    <td>
                        <a href="<?php echo $this->url('${nomeTabela}', array('action' => 'recover', 'id' => $${ctrlName}->${id})); ?>">Ver</a>
                        <a href="<?php echo $this->url('${nomeTabela}', array('action' => 'update', 'id' => $${ctrlName}->${id})); ?>">Editar</a>
                        <a href="<?php echo $this->url('${nomeTabela}', array('action' => 'delete', 'id' => $${ctrlName}->${id})); ?>">Apagar</a>
                    </td>
                </tr>
                <?php
            }
        }
        ?>
    </table>
    <?php
} else {
    echo '<h2>Sem Registros</h2>';
}
?>