<?php
/**             
 * Caminho module/${nomeModulo}/view/${nomeModulo}/${nomeTabela}/create.phtml
 */

$title = 'Adicionar ${nomeTabela}';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="collapse navbar-collapse">
	<ul class="nav navbar-nav">
	    <li>
	        <a href="<?php echo $this->url('${nomeTabela}', array('action'=>'list'));?>">  
	            <?php echo $this->translate('Listar registros') ?>
	        </a>
	    </li>
	</ul>
</div>
<br />

<?php
$form->setAttribute('action', $this->url('${nomeTabela}', array('action' => 'create')));
$form->prepare();

echo $this->form()->openTag($form);
${cpsNames}
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();