<?php echo $this->cabecalhoPagina('Listagem de Categorias', $this->botao('Cadastrar', $this->funcaoOnClick('kleo("cadastroCategoria", 0);'))); ?> 
<div class="content transition animate-panel fadeIn">   
  <div class="row">
    <div class="col-lg-12">
      <div class="hpanel">          
        <div class="panel-body">
          <table id="tabelaCategoriasParaAnalise" class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th>Data</th>
                <th>Nome</th>
              </tr>
            </thead>
            <tbody>
              <?php
              foreach($this->categorias as $categoria){
                echo '<tr>';
                echo '<td>'.$categoria->getData_criacaoFormatada(). '</td>';
                echo '<td>'.$categoria->getNome().'</td>';
                echo '</tr>';
              }
              ?>                                
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  window.onload = initPage;

  function initPage() {
    $('#tabelaCategoriasParaAnalise').dataTable();
  }
</script>