<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix userProfile">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="btn-group" role="group" aria-label="...">
                    <a href="account-dashboard.html" class="btn btn-default"><i class="fa fa-th" aria-hidden="true"></i>Relatórios</a>
                    <a href="account-profile.html" class="btn btn-default"><i class="fa fa-user" aria-hidden="true"></i>Perfil</a>
                    <a href="account-address.html" class="btn btn-default"><i class="fa fa-map-marker" aria-hidden="true"></i>Meu Endereço</a>
                    <a href="account-all-orders.html" class="btn btn-default active"><i class="fa fa-list" aria-hidden="true"></i>Análises Pendentes</a>
                    <a href="account-wishlist.html" class="btn btn-default"><i class="fa fa-gift" aria-hidden="true"></i>Lista de Desejos</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="innerWrapper singleOrder">
                    <div class="orderBox">
                        <h4>Order #451221</h4>
                    </div>
                    <div class="row">
                        <div class="col-sm-6 col-xs-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Endereço de Cobrança</h4>
                                </div>
                                <div class="panel-body">
                                    <address>
                                        <strong>Adam Smith</strong><br>
                                        9/4 C Babor Road, Mohammad pur, <br>
                                        Shyamoli, Dhaka <br>
                                        Bangladesh
                                    </address>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 col-xs-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Endereço de Entrega</h4>
                                </div>
                                <div class="panel-body">
                                    <address>
                                        <strong>Adam Smith</strong><br>
                                        9/4 C Babor Road, Mohammad pur, <br>
                                        Shyamoli, Dhaka <br>
                                        Bangladesh
                                    </address>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 col-xs-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Metodo de Pagamento</h4>
                                </div>
                                <div class="panel-body">
                                    <address>
                                        <span>Credit Card - VISA</span>
                                    </address>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 col-xs-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Metodo de Entrega</h4>
                                </div>
                                <div class="panel-body">
                                    <address>
                                        <span>Post Air Mail</span>
                                    </address>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Dados da Emrpesa</h4>
                                </div>
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="col-sm-4 col-xs-12">
                                            <address>
                                                <a href="#">Email: adamsmith@bigbag.com</a> <br>
                                                <span>Phone: +884 5452 6432</span>
                                            </address>
                                        </div>
                                        <div class="col-sm-8 col-xs-12">
                                            <address>
                                                <span>Additional Information: </span><br>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip</p>
                                            </address>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="btn-group" role="group" aria-label="...">
                                <button type="button" class="btn btn-default">Print</button>
                                <button type="button" class="btn btn-default">Save to pdf</button>
                                <button type="button" class="btn btn-default">cancel order</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>