<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix aboutUsInfo">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="page-header">
                    <h3>Cadastro realizado com sucesso!</h3>
                </div>
            </div>
            <div class="col-sm-6 col-sm-push-6 col-xs-12">
                <img src="/img/title-img.jpg" alt="about-us-img">
            </div>
            <div class="col-sm-6 col-sm-pull-6 col-xs-12">
                <p>Olá, Fulano obrigado por se cadastrar no ToNoShop.com.br</p>
                <p>Em breve entraremos em contato.</p>                
            </div>
        </div>
    </div>
</section>