<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix signUp">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading"><h3>seja um parceiro</h3></div>
                    <div class="panel-body">
                        <form action="/application/adm/empresaCadastrado" method="POST" role="form">
                            <?php
                            echo $this->inputFormulario('Nome Fantasia');
                            echo $this->inputFormulario('CNPJ');
                            echo $this->inputFormulario('Responsável');
                            echo $this->inputFormulario('Email');
                            echo $this->inputFormulario('Repetir Email');
                            echo $this->inputFormulario('DDD', 3);
                            echo $this->inputFormulario('Telefone', 9);
                            ?>
                            <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>