<!-- Simple splash screen-->
<div class="splash">
    <div class="color-line"></div>
    <div class="splash-title">
        <h1>www.tonoshop.com.br</h1>
        <div class="spinner"> 
            <div class="rect1"></div> 
            <div class="rect2"></div> 
            <div class="rect3"></div> 
            <div class="rect4"></div> 
            <div class="rect5"></div> 
        </div> 
    </div> 
</div>
<!--[if lt IE 7]>
<p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]--> 
<div class="color-line"></div> 
<div class="register-container">
    <div class="row">
        <div class="col-md-12">
            <div class="text-center m-b-md">
                <h3>Empresa</h3>
                <small>Cadastre sua empresa e conecte clientes potenciais a sua loja</small>
            </div>
            <div class="hpanel">
                <div class="panel-body">
                    <form action="/application/adm/empresaCadastrar" id="loginForm">
                        <div class="row">
                            <?php
                            echo $this->inputFormulario('Nome Fantasia');
                            echo $this->inputFormulario('CNPJ');
                            echo $this->inputFormulario('Razão Social');
                            echo $this->inputFormulario('CEP', 6);
                            echo $this->inputFormulario('Estado', 6);
                            echo $this->inputFormulario('Cidade', 6);
                            echo $this->inputFormulario('Bairro', 6);
                            echo $this->inputFormulario('Endereço');
                            echo $this->inputFormulario('Complemento');
                            echo $this->inputFormulario('Tem quantas filiais no Brasil?');
                            echo $this->inputFormulario('Nome do Responsável');
                            echo $this->inputFormulario('Email');
                            echo $this->inputFormulario('Repetir Email');
                            echo $this->inputFormulario('DDD', 3);
                            echo $this->inputFormulario('Celular', 9);
                            ?>
                        </div>
                        <div class="text-center">
                            <button class="btn btn-success">Cadastrar</button>
                            <button class="btn btn-default">Limpar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>