<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix signUp">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading"><h3>sing up</h3></div>
                    <div class="panel-body">
                        <form action="" method="POST" role="form">
                            <?php
                            echo $this->inputFormulario('Nome Fantasia');
                            echo $this->inputFormulario('CNPJ');
                            echo $this->inputFormulario('Razão Social');
                            echo $this->inputFormulario('CEP');
                            echo $this->inputFormulario('Complemento');
                            echo $this->inputFormulario('Filiais no Brasil?');
                            echo $this->inputFormulario('Responsável');
                            echo $this->inputFormulario('Email');
                            echo $this->inputFormulario('Repetir Email');
                            echo $this->inputFormulario('Celular');
                            ?>
                            <button type="submit" class="btn btn-primary btn-block">Enviar dados para Analise</button>
                            <button type="button" class="btn btn-link btn-block"><span>Já tenho uma conta?</span> Log in</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>