<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix userProfile">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="btn-group" role="group" aria-label="...">
                    <a href="account-dashboard.html" class="btn btn-default"><i class="fa fa-th" aria-hidden="true"></i>Relatórios</a>
                    <a href="account-profile.html" class="btn btn-default"><i class="fa fa-user" aria-hidden="true"></i>Perfil</a>
                    <a href="account-address.html" class="btn btn-default"><i class="fa fa-map-marker" aria-hidden="true"></i>Meu Endereço</a>
                    <a href="account-all-orders.html" class="btn btn-default active"><i class="fa fa-list" aria-hidden="true"></i>Análises Pendentes</a>
                    <a href="account-wishlist.html" class="btn btn-default"><i class="fa fa-gift" aria-hidden="true"></i>Lista de Desejos</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="innerWrapper">
                    <div class="orderBox">
                        <h4>Todas Análises</h4>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Data</th>
                                        <th>Empresa</th>
                                        <th>Responsavel</th>
                                        <th>Status</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>#451231</td>
                                        <td>19/12/2016</td>
                                        <td>Americanas.com.br</td>
                                        <td>Kort</td>
                                        <td><span class="label label-primary">Processing</span></td>
                                        <td><a href="#" class="btn btn-default">Ver</a></td>
                                    </tr>
                                    <tr>
                                        <td>#451231</td>
                                        <td>19/12/2016</td>
                                        <td>Casas Bahia</td>
                                        <td>Kort</td>
                                        <td><span class="label label-success">Completed</span></td>
                                        <td><a href="#" class="btn btn-default">Ver</a></td>
                                    </tr>
                                    <tr>
                                        <td>#451231</td>
                                        <td>19/12/2016</td>
                                        <td>Riachuelo</td>
                                        <td>Kort</td>
                                        <td><span class="label label-danger">Canceled</span></td>
                                        <td><a href="#" class="btn btn-default">Ver</a></td>
                                    </tr>
                                    <tr>
                                        <td>#451231</td>
                                        <td>19/12/2016</td>
                                        <td>Mont Blanck</td>
                                        <td>Kort</td>
                                        <td><span class="label label-info">On Hold</span></td>
                                        <td><a href="#" class="btn btn-default">Ver</a></td>
                                    </tr>
                                    <tr>
                                        <td>#451231</td>
                                        <td>19/12/2016</td>
                                        <td>Outback</td>
                                        <td>Kort</td>
                                        <td><span class="label label-warning">Pending</span></td>
                                        <td><a href="#" class="btn btn-default">Ver</a></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>