<?php

use Application\Form\KleoForm;

$formulario = $this->formulario;
$formulario->prepare();

$formulario->setAttribute(KleoForm::stringAction, 'admLojaFinalizar');
echo $this->form()->openTag($formulario);
echo $this->formHidden($formulario->get(KleoForm::inputCSRF));
echo $this->formHidden($formulario->get(KleoForm::inputId));
?>
<?php echo $this->cabecalhoPagina('Cadastrar Matriz ou Filial'); ?> 
<div class="content animate-panel">
  <div class="row">
    <div class="col-md-12">
      <div class="hpanel">
        <div class="panel-body">
          <?php
          echo $this->inputFormulario(KleoForm::traducaoDDD, $formulario->get(KleoForm::inputDDD), 3);
          echo $this->inputFormulario(KleoForm::traducaoTelefone, $formulario->get(KleoForm::inputTelefone), 9);
          echo $this->inputFormulario(KleoForm::traducaoCNPJ, $formulario->get(KleoForm::inputCNPJ));
          echo $this->inputFormulario(KleoForm::traducaoShopping, $formulario->get(KleoForm::inputShoppingId));
          echo $this->botao('Cadastrar', $this->funcaoOnClickSubmeterFormulario());
          echo $this->botao('Voltar', $this->funcaoOnClick('mudarPaginaComLoader("/admLojas")'), 2);
          ?>
        </div>
      </div>
    </div>
  </div>
</div>
<?php
echo $this->form()->closeTag();