<!-- Simple splash screen-->
<div class="splash"> <div class="color-line"></div><div class="splash-title"><h1>Homer - Responsive Admin Theme</h1><p>Special Admin Theme for small and medium webapp with very clean and aesthetic style and feel. </p><div class="spinner"> <div class="rect1"></div> <div class="rect2"></div> <div class="rect3"></div> <div class="rect4"></div> <div class="rect5"></div> </div> </div> </div>
<!--[if lt IE 7]>
<p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<div class="color-line"></div>
<div class="register-container">
    <div class="row">
        <div class="col-md-12">
            <div class="text-center m-b-md">
                <h3>Cadastrar Shopping</h3>
            </div>
            <div class="hpanel">
                <div class="panel-body">
                    <form action="/application/adm/shoppings" id="loginForm">
                        <div class="row">
                            <?php
                            echo $this->inputFormulario('Nome do Shopping');
                            ?>
                            <div class="form-group col-lg-6">
                                <label>Estado</label>
                                <select class="form-control">
                                    <option>DF</option>
                                    <option>SP</option>
                                </select>
                            </div>
                            <div class="form-group col-lg-6">
                                <label>Status</label>
                                <select class="form-control">
                                    <option>Ativo</option>
                                    <option>Inativo</option>
                                </select>
                            </div>
                        </div>
                        <div class="text-center">
                            <button class="btn btn-success">Cadastrar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>   
</div>