<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Administração')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Styles -->      
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/styles/style.css'))
                ->prependStylesheet($this->basePath('fonts/pe-icon-7-stroke/css/helper.css'))
                ->prependStylesheet($this->basePath('fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css'))
                ->prependStylesheet($this->basePath('plugins/datatables.net-bs/css/dataTables.bootstrap.min.css'))
                ->prependStylesheet($this->basePath('plugins/bootstrap/dist/css/bootstrap.css'))
                ->prependStylesheet($this->basePath('plugins/animate.css/animate.min.css'))
                ->prependStylesheet($this->basePath('plugins/metisMenu/dist/metisMenu.css'))
                ->prependStylesheet($this->basePath('plugins/fontawesome/css/font-awesome.css'))
        ;
        ?>
    </head>
    <body class="blank fixed-navbar fixed-sidebar">
        <?php echo $this->content; ?>       
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/homer.js'))
                ->prependFile($this->basePath('plugins/datatables.net-buttons-bs/js/buttons.bootstrap.min.js'))
                ->prependFile($this->basePath('plugins/datatables.net-buttons/js/dataTables.buttons.min.js'))
                ->prependFile($this->basePath('plugins/datatables.net-buttons/js/buttons.print.min.js'))
                ->prependFile($this->basePath('plugins/datatables.net-buttons/js/buttons.html5.min.js'))
                ->prependFile($this->basePath('plugins/datatables.net-bs/js/dataTables.bootstrap.min.js'))
                ->prependFile($this->basePath('plugins/datatables/media/js/jquery.dataTables.min.js'))
                ->prependFile($this->basePath('plugins/sparkline/index.js'))
                ->prependFile($this->basePath('plugins/iCheck/icheck.min.js'))
                ->prependFile($this->basePath('plugins/metisMenu/dist/metisMenu.min.js'))
                ->prependFile($this->basePath('plugins/bootstrap/dist/js/bootstrap.min.js'))
                ->prependFile($this->basePath('plugins/slimScroll/jquery.slimscroll.min.js'))
                ->prependFile($this->basePath('plugins/jquery-ui/jquery-ui.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
        ;
        echo $this->inlineScript();
        ?>
    </body>
</html>
