<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ToNoShop')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/colors/default.css'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('plugins/rs-plugin/css/settings.css'))
                ->prependStylesheet($this->basePath('plugins/selectbox/select_option1.css'))
                ->prependStylesheet($this->basePath('plugins/owl-carousel/owl.carousel.css'))
                ->prependStylesheet($this->basePath('plugins/jquery-ui/jquery-ui.css'))
                ->prependStylesheet($this->basePath('plugins/bootstrapBigbag/css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('plugins/font-awesome/css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/colors/default.css'))
                ->prependStylesheet('https://fonts.googleapis.com/css?family=Oxygen:400,300,700');
        ?>
    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/custom.js'))
                ->prependFile($this->basePath('plugins/countdown/jquery.syotimer.js'))
                ->prependFile($this->basePath('plugins/selectbox/jquery.selectbox-0.1.3.min.js'))
                ->prependFile($this->basePath('plugins/owl-carousel/owl.carousel.js'))
                ->prependFile($this->basePath('plugins/rs-plugin/js/jquery.themepunch.revolution.min.js'))
                ->prependFile($this->basePath('plugins/rs-plugin/js/jquery.themepunch.tools.min.js'))
                ->prependFile($this->basePath('plugins/bootstrapBigbag/js/bootstrap.min.js'))
                ->prependFile($this->basePath('plugins/jquery-ui/jquery-ui.js'))
                ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js');
        echo $this->inlineScript();
        ?>
    </body>
</html>
