<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Administração')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Styles -->      
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/styles/style.css'))
                ->prependStylesheet($this->basePath('fonts/pe-icon-7-stroke/css/helper.css'))
                ->prependStylesheet($this->basePath('fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css'))
                ->prependStylesheet($this->basePath('plugins/datatables.net-bs/css/dataTables.bootstrap.min.css'))
                ->prependStylesheet($this->basePath('plugins/bootstrap/dist/css/bootstrap.css'))
                ->prependStylesheet($this->basePath('plugins/animate.css/animate.min.css'))
                ->prependStylesheet($this->basePath('plugins/metisMenu/dist/metisMenu.css'))
                ->prependStylesheet($this->basePath('plugins/fontawesome/css/font-awesome.css'))
        ;
        ?>
    </head>
    <body class="blank fixed-navbar fixed-sidebar">

        <!-- Simple splash screen-->
        <div class="splash">
            <div class="color-line"></div>
            <div class="splash-title">
                <h1>www.tonoshop.com.br</h1>
                <div class="spinner"> 
                    <div class="rect1"></div> 
                    <div class="rect2"></div> 
                    <div class="rect3"></div> 
                    <div class="rect4"></div> 
                    <div class="rect5"></div> 
                </div> 
            </div> 
        </div>
        <!--[if lt IE 7]>
        <p class="alert alert-danger">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <!-- Header -->
        <div id="header">
            <div class="color-line">
            </div>
            <div id="logo" class="light-version">
                <span>
                    Homer Theme
                </span>
            </div>
            <nav role="navigation">
                <div class="header-link hide-menu"><i class="fa fa-bars"></i></div>
                <div class="small-logo">
                    <span class="text-primary">HOMER APP</span>
                </div>
                <div class="mobile-menu">
                    <button type="button" class="navbar-toggle mobile-menu-toggle" data-toggle="collapse" data-target="#mobile-collapse">
                        <i class="fa fa-chevron-down"></i>
                    </button>
                    <div class="collapse mobile-navbar" id="mobile-collapse">
                        <ul class="nav navbar-nav">
                            <li>
                                <a class="" href="login.html">Login</a>
                            </li>
                            <li>
                                <a class="" href="login.html">Logout</a>
                            </li>
                            <li>
                                <a class="" href="profile.html">Profile</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="navbar-right">
                    <ul class="nav navbar-nav no-borders">
                        <li class="dropdown">
                            <a href="login.html">
                                <i class="pe-7s-upload pe-rotate-90"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <!-- Navigation -->
        <aside id="menu">
            <div id="navigation">
                <div class="profile-picture">
                    <a href="index.html">
                        <!--<img src="images/profile.jpg" class="img-circle m-b" alt="logo">-->
                        KLEO
                    </a>

                    <div class="stats-label text-color">
                        <span class="font-extra-bold font-uppercase">Kort e Léo</span>

                        <div class="dropdown">
                            <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                                <small class="text-muted">Founder of App <b class="caret"></b></small>
                            </a>
                            <ul class="dropdown-menu animated flipInX m-t-xs">
                                <li><a href="contacts.html">Contacts</a></li>
                                <li><a href="profile.html">Profile</a></li>
                                <li><a href="analytics.html">Analytics</a></li>
                                <li class="divider"></li>
                                <li><a href="login.html">Logout</a></li>
                            </ul>
                        </div>


                        <div id="sparkline1" class="small-chart m-t-sm"></div>
                        <div>
                            <h4 class="font-extra-bold m-b-xs">
                                $260 104,200
                            </h4>
                            <small class="text-muted">Your income from the last year in sales product X.</small>
                        </div>
                    </div>
                </div>
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="#"><span class="nav-label">Cadastro</span><span class="fa arrow"></span> </a>
                        <ul class="nav nav-second-level">
                            <li><a href="/cadastroShoppings">Shoppings</a></li>
                            <li><a href="/cadastroEmpresas">Empresas</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </aside>
        <?php echo $this->content; ?>       
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/homer.js'))
                ->prependFile($this->basePath('plugins/datatables.net-buttons-bs/js/buttons.bootstrap.min.js'))
                ->prependFile($this->basePath('plugins/datatables.net-buttons/js/dataTables.buttons.min.js'))
                ->prependFile($this->basePath('plugins/datatables.net-buttons/js/buttons.print.min.js'))
                ->prependFile($this->basePath('plugins/datatables.net-buttons/js/buttons.html5.min.js'))
                ->prependFile($this->basePath('plugins/datatables.net-bs/js/dataTables.bootstrap.min.js'))
                ->prependFile($this->basePath('plugins/datatables/media/js/jquery.dataTables.min.js'))
                ->prependFile($this->basePath('plugins/sparkline/index.js'))
                ->prependFile($this->basePath('plugins/iCheck/icheck.min.js'))
                ->prependFile($this->basePath('plugins/metisMenu/dist/metisMenu.min.js'))
                ->prependFile($this->basePath('plugins/bootstrap/dist/js/bootstrap.min.js'))
                ->prependFile($this->basePath('plugins/slimScroll/jquery.slimscroll.min.js'))
                ->prependFile($this->basePath('plugins/jquery-ui/jquery-ui.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
        ;
        echo $this->inlineScript();
        ?>
    </body>
</html>
