<?php

use Application\Form\KleoForm;

$formulario = $this->formulario;
$formulario->prepare();

$formulario->setAttribute(KleoForm::stringAction, 'pubResponsavelFinalizar');
echo $this->form()->openTag($formulario);
echo $this->formHidden($formulario->get(KleoForm::inputCSRF));
echo $this->formHidden($formulario->get(KleoForm::inputId));
?>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix signUp">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading"><h3>seja um parceiro</h3></div>
          <div class="panel-body">                       
            <?php
            echo $this->inputFormulario(KleoForm::traducaoNome, $formulario->get(KleoForm::inputNome));
            echo $this->inputFormulario(KleoForm::traducaoDDD, $formulario->get(KleoForm::inputDDD), 3);
            echo $this->inputFormulario(KleoForm::traducaoTelefone, $formulario->get(KleoForm::inputTelefone), 9);
            echo $this->inputFormulario(KleoForm::traducaoEmail, $formulario->get(KleoForm::inputEmail));
            echo $this->inputFormulario(KleoForm::traducaoRepetirEmail, $formulario->get(KleoForm::inputRepetirEmail));
            echo $this->inputFormulario(KleoForm::traducaoNomeFantasia, $formulario->get(KleoForm::inputNomeFantasia));
            echo $this->inputFormulario(KleoForm::traducaoCNPJ, $formulario->get(KleoForm::inputCNPJ));
            echo $this->botao('Cadastrar', $this->funcaoOnClickSubmeterFormulario());
            ?>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<?php
echo $this->form()->closeTag();