<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix signUp">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading"><h3>Cadastro Concluído com sucesso!</h3></div>
                    <div class="panel-body text-center">
                          Em breve entraremos em contato.
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>