<!-- CONTENT SECTION -->
<section class="content clearfix">
  <div class="container">

    <!-- FEATURE COLLECTION SECTION -->
    <div class="row featuredCollection version2 version3">
      <div class="col-sm-6 col-xs-12">
        <div class="slide">
          <div class="productImage productImage1">
          </div>
          <div class="productCaption clearfix text-right">
            <h3><a href="single-product.html">women’s Shoes</a></h3>
            <p>Lorem ipsum dolor sit ameit</p>
            <a href="single-product.html" class="btn btn-border">Shop Now</a>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-xs-12">
        <div class="slide">
          <div class="productImage productImage2">
          </div>
          <div class="productCaption clearfix text-right">
            <h3><a href="single-product.html">Headphone wifi</a></h3>
            <p>Lorem ipsum dolor sit ameit</p>
            <a href="single-product.html" class="btn btn-border">Shop Now</a>
          </div>
        </div>
      </div>
    </div>

    <!-- CATEGORY SECTION -->
    <div class="categorySection">
      <div class="row">
        <div class="col-md-6 col-xs-12">
          <div class="category-content">
            <div class="category-top">
              <div class="category-menu text-center">
                <h2 class="category-title">Men’s Clothing</h2>
                <ul>
                  <li><a href="product-grid-left-sidebar.html">Down Jackets</a></li>
                  <li><a href="product-grid-left-sidebar.html">T Shirts</a></li>
                  <li><a href="product-grid-left-sidebar.html">Jeans</a></li>
                  <li><a href="product-grid-left-sidebar.html">Casual Pants</a></li>
                  <li><a href="product-grid-left-sidebar.html">Sunglasses</a></li>
                  <li><a href="product-grid-left-sidebar.html">Hoodies</a></li>
                </ul>
              </div>
              <div class="category-Slider">
                <div class="owl-carousel categorySlider">
                  <div class="item">
                    <img src="img/home/category/category-img3.jpg" alt="Image">
                  </div>
                  <div class="item">
                    <img src="img/home/category/category-img3.jpg" alt="Image">
                  </div>
                </div>
              </div>
            </div>

            <div class="category-bottom">
              <div class="imageBox">
                <div class="productImage clearfix">
                  <a href="single-product.html">
                    <img src="img/home/category/category-img6.jpg" alt="Image">
                  </a>
                  <div class="productMasking">
                    <ul class="list-inline btn-group" role="group">
                      <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                      <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                      <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-search"></i></a></li>
                    </ul>
                  </div>
                </div>
                <div class="productCaption clearfix">
                  <h5><a href="single-product.html">Nike Sportswear</a></h5>
                  <h3>$199</h3>
                </div>
              </div>
              <div class="imageBox">
                <div class="productImage clearfix">
                  <a href="single-product.html">
                    <img src="img/home/category/category-img7.jpg" alt="Image">
                  </a>
                  <span class="sticker">50% off</span>
                  <div class="productMasking">
                    <ul class="list-inline btn-group" role="group">
                      <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                      <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                      <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-search"></i></a></li>
                    </ul>
                  </div>
                </div>
                <div class="productCaption clearfix">
                  <h5><a href="single-product.html">Nike Sportswear</a></h5>
                  <h3>$199</h3>
                </div>
              </div>
              <div class="imageBox">
                <div class="productImage clearfix">
                  <a href="single-product.html">
                    <img src="img/home/category/category-img8.jpg" alt="Image">
                  </a>
                  <div class="productMasking">
                    <ul class="list-inline btn-group" role="group">
                      <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                      <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                      <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-search"></i></a></li>
                    </ul>
                  </div>
                </div>
                <div class="productCaption clearfix">
                  <h5><a href="single-product.html">Nike Sportswear</a></h5>
                  <h3>$199</h3>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-6 col-xs-12">
          <div class="category-content">
            <div class="category-top">
              <div class="category-menu text-center">
                <h2 class="category-title">woMen’s Clothing</h2>
                <ul>
                  <li><a href="product-grid-left-sidebar.html">Casual Dresses</a></li>
                  <li><a href="product-grid-left-sidebar.html">Sweaters</a></li>
                  <li><a href="product-grid-left-sidebar.html">Coats & Jackets</a></li>
                  <li><a href="product-grid-left-sidebar.html">Cosmetic</a></li>
                  <li><a href="product-grid-left-sidebar.html">T Shirts</a></li>
                  <li><a href="product-grid-left-sidebar.html">Shoes</a></li>
                </ul>
              </div>
              <div class="category-Slider">
                <div class="owl-carousel categorySlider">
                  <div class="item">
                    <img src="img/home/category/category-img2.jpg" alt="Image">
                  </div>
                  <div class="item">
                    <img src="img/home/category/category-img2.jpg" alt="Image">
                  </div>
                </div>
              </div>
            </div>

            <div class="category-bottom">
              <div class="imageBox">
                <div class="productImage clearfix">
                  <a href="single-product.html">
                    <img src="img/home/category/category-img9.jpg" alt="Image">
                  </a>
                  <span class="sticker">50% off</span>
                  <div class="productMasking">
                    <ul class="list-inline btn-group" role="group">
                      <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                      <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                      <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-search"></i></a></li>
                    </ul>
                  </div>
                </div>
                <div class="productCaption clearfix">
                  <h5><a href="single-product.html">Nike Sportswear</a></h5>
                  <h3>$199</h3>
                </div>
              </div>
              <div class="imageBox">
                <div class="productImage clearfix">
                  <a href="single-product.html">
                    <img src="img/home/category/category-img10.jpg" alt="Image">
                  </a>
                  <div class="productMasking">
                    <ul class="list-inline btn-group" role="group">
                      <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                      <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                      <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-search"></i></a></li>
                    </ul>
                  </div>
                </div>
                <div class="productCaption clearfix">
                  <h5><a href="single-product.html">Nike Sportswear</a></h5>
                  <h3>$199</h3>
                </div>
              </div>
              <div class="imageBox">
                <div class="productImage clearfix">
                  <a href="single-product.html">
                    <img src="img/home/category/category-img11.jpg" alt="Image">
                  </a>
                  <div class="productMasking">
                    <ul class="list-inline btn-group" role="group">
                      <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                      <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                      <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-search"></i></a></li>
                    </ul>
                  </div>
                </div>
                <div class="productCaption clearfix">
                  <h5><a href="single-product.html">Nike Sportswear</a></h5>
                  <h3>$199</h3>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-6 col-xs-12">
          <div class="category-content">
            <div class="category-top">
              <div class="category-menu text-center">
                <h2 class="category-title">Jewelry Collections</h2>
                <ul>
                  <li><a href="product-grid-left-sidebar.html">Jewlery Sets</a></li>
                  <li><a href="product-grid-left-sidebar.html">Earring Sets</a></li>
                  <li><a href="product-grid-left-sidebar.html">DIY Jewelry</a></li>
                  <li><a href="product-grid-left-sidebar.html">Pendant Nacklaces</a></li>
                  <li><a href="product-grid-left-sidebar.html">Popupar Bracelets</a></li>
                  <li><a href="product-grid-left-sidebar.html">Pendant</a></li>
                </ul>
              </div>
              <div class="category-Slider">
                <div class="owl-carousel categorySlider">
                  <div class="item">
                    <img src="img/home/category/category-img4.jpg" alt="Image">
                  </div>
                  <div class="item">
                    <img src="img/home/category/category-img4.jpg" alt="Image">
                  </div>
                </div>
              </div>
            </div>

            <div class="category-bottom">
              <div class="imageBox">
                <div class="productImage clearfix">
                  <a href="single-product.html">
                    <img src="img/home/category/category-img13.jpg" alt="Image">
                  </a>
                  <span class="sticker">50% off</span>
                  <div class="productMasking">
                    <ul class="list-inline btn-group" role="group">
                      <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                      <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                      <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-search"></i></a></li>
                    </ul>
                  </div>
                </div>
                <div class="productCaption clearfix">
                  <h5><a href="single-product.html">Nike Sportswear</a></h5>
                  <h3>$199</h3>
                </div>
              </div>
              <div class="imageBox">
                <div class="productImage clearfix">
                  <a href="single-product.html">
                    <img src="img/home/category/category-img14.jpg" alt="Image">
                  </a>
                  <div class="productMasking">
                    <ul class="list-inline btn-group" role="group">
                      <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                      <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                      <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-search"></i></a></li>
                    </ul>
                  </div>
                </div>
                <div class="productCaption clearfix">
                  <h5><a href="single-product.html">Nike Sportswear</a></h5>
                  <h3>$199</h3>
                </div>
              </div>
              <div class="imageBox">
                <div class="productImage clearfix">
                  <a href="single-product.html">
                    <img src="img/home/category/category-img12.jpg" alt="Image">
                  </a>
                  <div class="productMasking">
                    <ul class="list-inline btn-group" role="group">
                      <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                      <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                      <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-search"></i></a></li>
                    </ul>
                  </div>
                </div>
                <div class="productCaption clearfix">
                  <h5><a href="single-product.html">Nike Sportswear</a></h5>
                  <h3>$199</h3>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-6 col-xs-12">
          <div class="category-content">
            <div class="category-top">
              <div class="category-menu text-center">
                <h2 class="category-title">Bags & Shoes</h2>
                <ul>
                  <li><a href="product-grid-left-sidebar.html">Women’s Boots</a></li>
                  <li><a href="product-grid-left-sidebar.html">Women’s Casual Shoes</a></li>
                  <li><a href="product-grid-left-sidebar.html">Women’s Bags</a></li>
                  <li><a href="product-grid-left-sidebar.html">Men’s Boots</a></li>
                  <li><a href="product-grid-left-sidebar.html">Men’s Casual Shoes</a></li>
                  <li><a href="product-grid-left-sidebar.html">Men’s Bags</a></li>
                </ul>
              </div>
              <div class="category-Slider">
                <div class="owl-carousel categorySlider">
                  <div class="item">
                    <img src="img/home/category/category-img5.jpg" alt="Image">
                  </div>
                  <div class="item">
                    <img src="img/home/category/category-img5.jpg" alt="Image">
                  </div>
                </div>
              </div>
            </div>

            <div class="category-bottom">
              <div class="imageBox">
                <div class="productImage clearfix">
                  <a href="single-product.html">
                    <img src="img/home/category/category-img16.jpg" alt="Image">
                  </a>
                  <span class="sticker">50% off</span>
                  <div class="productMasking">
                    <ul class="list-inline btn-group" role="group">
                      <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                      <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                      <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-search"></i></a></li>
                    </ul>
                  </div>
                </div>
                <div class="productCaption clearfix">
                  <h5><a href="single-product.html">Nike Sportswear</a></h5>
                  <h3>$199</h3>
                </div>
              </div>
              <div class="imageBox">
                <div class="productImage clearfix">
                  <a href="single-product.html">
                    <img src="img/home/category/category-img17.jpg" alt="Image">
                  </a>
                  <div class="productMasking">
                    <ul class="list-inline btn-group" role="group">
                      <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                      <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                      <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-search"></i></a></li>
                    </ul>
                  </div>
                </div>
                <div class="productCaption clearfix">
                  <h5><a href="single-product.html">Nike Sportswear</a></h5>
                  <h3>$199</h3>
                </div>
              </div>
              <div class="imageBox">
                <div class="productImage clearfix">
                  <a href="single-product.html">
                    <img src="img/home/category/category-img15.jpg" alt="Image">
                  </a>
                  <div class="productMasking">
                    <ul class="list-inline btn-group" role="group">
                      <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                      <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                      <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-search"></i></a></li>
                    </ul>
                  </div>
                </div>
                <div class="productCaption clearfix">
                  <h5><a href="single-product.html">Nike Sportswear</a></h5>
                  <h3>$199</h3>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>  
    </div>

  </div>
</section>