<!-- HEADER -->
<div class="header clearfix">

    <!-- TOPBAR -->
    <div class="topBar">
        <div class="container">
            <div class="row">
                <div class="col-md-6 hidden-sm hidden-xs">
                    <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                        <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
                        <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
                    </ul>
                </div>
                <div class="col-md-6 col-xs-12">
                    <ul class="list-inline pull-right top-right">
                        <li class="account-login"><span><a data-toggle="modal" href='.login-modal'>Log in</a><small>or</small><a data-toggle="modal" href='#signup'>Create an account</a></span></li>
                        <li class="searchBox">
                            <a href="#"><i class="fa fa-search"></i></a>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <li>
                                    <span class="input-group">
                                        <input type="text" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                                        <button type="submit" class="input-group-addon">Submit</button>
                                    </span>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown cart-dropdown">
                            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i>$0</a>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <li>Item(s) in your cart</li>
                                <li>
                                    <a href="single-product.html">
                                        <div class="media">
                                            <img class="media-left media-object" src="img/home/cart-items/cart-item-01.jpg" alt="cart-Image">
                                            <div class="media-body">
                                                <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="single-product.html">
                                        <div class="media">
                                            <img class="media-left media-object" src="img/home/cart-items/cart-item-01.jpg" alt="cart-Image">
                                            <div class="media-body">
                                                <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <div class="btn-group" role="group" aria-label="...">
                                        <button type="button" class="btn btn-default" onclick="location.href = 'cart-page.html';">Shopping Cart</button>
                                        <button type="button" class="btn btn-default" onclick="location.href = 'checkout-step-1.html';">Checkout</button>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>    
    </div>

    <!-- NAVBAR -->
    <nav class="navbar navbar-main navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index-v1.html"><img src="img/logo.png" alt="logo"></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">            
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown active">
                        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Home</a>
                        <ul class="dropdown-menu dropdown-menu-left">
                            <li class="active"><a href="index-v1.html">Home Default</a></li>
                            <li><a href="index-v2.html">Home Classic</a></li>
                            <li><a href="index-v3.html">Home Deals</a></li>
                            <li><a href="index-v4.html">Home Mega</a></li>
                        </ul>
                    </li>
                    <li class="dropdown megaDropMenu">
                        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</b></a>
                        <ul class="dropdown-menu row">
                            <li class="col-sm-3 col-xs-12">
                                <ul class="list-unstyled">
                                    <li>Products Grid View</li>
                                    <li><a href="product-grid-left-sidebar.html">Products Sidebar Left</a></li>
                                    <li><a href="product-grid-right-sidebar.html">Products Sidebar Right</a></li>
                                    <li><a href="product-grid-3-col-filter.html">Products 3 Columns V1</a></li>
                                    <li><a href="product-grid-3-col.html">Products 3 Columns V2</a></li>
                                    <li><a href="product-grid-4-col.html">Products 4 Columns</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-3 col-xs-12">
                                <ul class="list-unstyled">
                                    <li>Products List View</li>
                                    <li><a href="product-list-left-sidebar.html">Products Sidebar Left</a></li>
                                    <li><a href="product-list-right-sidebar.html">Products Sidebar Right</a></li>
                                    <li class="listHeading">Others</li>
                                    <li><a href="single-product.html">Single Product</a></li>
                                    <li><a href="cart-page.html">Cart Page</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-3 col-xs-12">
                                <ul class="list-unstyled">
                                    <li>Checkout</li>
                                    <li><a href="checkout-step-1.html">Step 1 - Address</a></li>
                                    <li><a href="checkout-step-2.html">Step 2 - Shipping</a></li>
                                    <li><a href="checkout-step-3.html">Step 3 - Payment</a></li>
                                    <li><a href="checkout-step-4.html">Step 4 - Payment</a></li>
                                    <li><a href="checkout-complete.html">Order Complete</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-3 col-xs-12">
                                <a href="#" class="menu-photo"><img src="img/menu-photo.jpg" alt="menu-img"></a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">pages</a>
                        <ul class="dropdown-menu dropdown-menu-left">
                            <li><a href="about-us.html">About Us</a></li>
                            <li><a href="signup.html">Register</a></li>
                            <li><a href="signup-login.html">Register or Login</a></li>
                            <li><a href="login.html">Login</a></li>
                            <li><a href="lost-password.html">Password Recovery</a></li>
                            <li><a href="privacy-policy.html">Privacy Policy</a></li>
                            <li><a href="terms-and-conditions.html">Terms &amp; Conditions</a></li>
                            <li><a href="404.html">404 Not Found</a></li>
                            <li><a href="short-code.html">Short Code</a></li>
                            <li><a href="coming-soon.html">Coming Soon</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">blog</a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="blog-right-sidebar.html">Right Sidebar</a></li>
                            <li><a href="blog-left-sidebar.html">Left Sidebar</a></li>
                            <li><a href="blog-fullwidth.html">Full Width</a></li>
                            <li><a href="blog-single-fullwidth.html">Single Post</a></li>
                            <li><a href="blog-single-right-sidebar.html">Single Right Sidebar</a></li>
                            <li><a href="blog-single-left-sidebar.html">Single Left Sidebar</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account</a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="account-dashboard.html">Dashboard</a></li>
                            <li><a href="account-profile.html">Profile</a></li>
                            <li><a href="account-all-orders.html">All Orders</a></li>
                            <li><a href="account-single-order.html">Single Order</a></li>
                            <li><a href="account-wishlist.html">Wishlist</a></li>
                            <li><a href="account-address.html">Address</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div>
    </nav>

</div>

<div class="main-wrapper">

    <!-- BANNER -->
    <div class="bannercontainer bannerV1">
        <div class="fullscreenbanner-container">
            <div class="fullscreenbanner">
                <ul>
                    <li data-transition="slidehorizontal" data-slotamount="5" data-masterspeed="700" data-title="Slide 1">
                        <img src="img/home/banner-slider/slider-bg.jpg" alt="slidebg1" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
                        <div class="slider-caption slider-captionV1 container">

                            <div class="tp-caption rs-caption-1 sft start" 
                                 data-hoffset="0" 
                                 data-x="370" 
                                 data-y="54" 
                                 data-speed="800" 
                                 data-start="1500" 
                                 data-easing="Back.easeInOut" 
                                 data-endspeed="300" >
                                <img src="img/home/banner-slider/shoe1.png" alt="slider-image" style="width: 781px; height: 416px;">
                            </div>

                            <div class="tp-caption rs-caption-2 sft"
                                 data-hoffset="0"
                                 data-y="119"
                                 data-speed="800"
                                 data-start="2000"
                                 data-easing="Back.easeInOut"
                                 data-endspeed="300">
                                Canvas Sneaker
                            </div>

                            <div class="tp-caption rs-caption-3 sft"
                                 data-hoffset="0"
                                 data-y="185"
                                 data-speed="1000"
                                 data-start="3000"
                                 data-easing="Power4.easeOut"
                                 data-endspeed="300"
                                 data-endeasing="Power1.easeIn"
                                 data-captionhidden="off">
                                Exclusive to <br>
                                BigBag <br>
                                <small>Spring / Summer 2016</small>
                            </div>
                            <div class="tp-caption rs-caption-4 sft"
                                 data-hoffset="0"
                                 data-y="320"
                                 data-speed="800"
                                 data-start="3500"
                                 data-easing="Power4.easeOut"
                                 data-endspeed="300"
                                 data-endeasing="Power1.easeIn"
                                 data-captionhidden="off">
                                <span class="page-scroll"><a href="#" class="btn primary-btn">Buy Now<i class="glyphicon glyphicon-chevron-right"></i></a></span>
                            </div>
                        </div>
                    </li>
                    <li data-transition="slidehorizontal" data-slotamount="5" data-masterspeed="1000" data-title="Slide 2">
                        <img src="img/home/banner-slider/slider-bg.jpg" alt="slidebg" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
                        <div class="slider-caption slider-captionV1 container captionCenter">
                            <div class="tp-caption rs-caption-1 sft start text-center"
                                 data-x="center"
                                 data-y="228"
                                 data-speed="800"
                                 data-start="1500"
                                 data-easing="Back.easeInOut"
                                 data-endspeed="300">
                                <img src="img/home/banner-slider/shoe2.png" alt="slider-image">
                            </div>

                            <div class="tp-caption rs-caption-2 sft text-center"
                                 data-x="center"
                                 data-y="50"
                                 data-speed="800"
                                 data-start="2000"
                                 data-easing="Back.easeInOut"
                                 data-endspeed="300">
                                Exclusive to BigBag
                            </div>

                            <div class="tp-caption rs-caption-3 sft text-center"
                                 data-x="center"
                                 data-y="98"
                                 data-speed="1000"
                                 data-start="3000"
                                 data-easing="Power4.easeOut"
                                 data-endspeed="300"
                                 data-endeasing="Power1.easeIn"
                                 data-captionhidden="off">
                                Canvas Sneaker
                            </div>

                            <div class="tp-caption rs-caption-4 sft text-center"
                                 data-x="center"
                                 data-y="156"
                                 data-speed="800"
                                 data-start="3500"
                                 data-easing="Power4.easeOut"
                                 data-endspeed="300"
                                 data-endeasing="Power1.easeIn"
                                 data-captionhidden="off">
                                <span class="page-scroll"><a href="#" class="btn primary-btn">Buy Now<i class="glyphicon glyphicon-chevron-right"></i></a></span>
                            </div>
                        </div>
                    </li>
                    <li data-transition="slidehorizontal" data-slotamount="5" data-masterspeed="700"  data-title="Slide 3">
                        <img src="img/home/banner-slider/slider-bg.jpg" alt="slidebg" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
                        <div class="slider-caption slider-captionV1 container">
                            <div class="tp-caption rs-caption-1 sft start"
                                 data-hoffset="0"
                                 data-y="85"
                                 data-speed="800"
                                 data-start="1500"
                                 data-easing="Back.easeInOut"
                                 data-endspeed="300">
                                <img src="img/home/banner-slider/shoe3.png" alt="slider-image">
                            </div>

                            <div class="tp-caption rs-caption-2 sft "
                                 data-hoffset="0"
                                 data-y="119"
                                 data-x="800"
                                 data-speed="800"
                                 data-start="2000"
                                 data-easing="Back.easeInOut"
                                 data-endspeed="300">
                                Canvas Sneaker
                            </div>

                            <div class="tp-caption rs-caption-3 sft"
                                 data-hoffset="0"
                                 data-y="185"
                                 data-x="800"
                                 data-speed="1000"
                                 data-start="3000"
                                 data-easing="Power4.easeOut"
                                 data-endspeed="300"
                                 data-endeasing="Power1.easeIn"
                                 data-captionhidden="off">
                                Exclusive to <br>
                                BigBag <br>
                                <small>Spring / Summer 2016</small>
                            </div>

                            <div class="tp-caption rs-caption-4 sft"
                                 data-hoffset="0"
                                 data-y="320"
                                 data-x="800"
                                 data-speed="800"
                                 data-start="3500"
                                 data-easing="Power4.easeOut"
                                 data-endspeed="300"
                                 data-endeasing="Power1.easeIn"
                                 data-captionhidden="off">
                                <span class="page-scroll"><a href="#" class="btn primary-btn">Buy Now<i class="glyphicon glyphicon-chevron-right"></i></a></span>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!-- MAIN CONTENT SECTION -->
    <section class="mainContent clearfix">
        <div class="container">
            <div class="row featuredCollection margin-bottom">
                <div class="col-xs-12">
                    <div class="page-header">
                        <h4>Featured Collection</h4>
                    </div>
                </div>
                <div class="col-sm-4 col-xs-12">
                    <div class="thumbnail" onclick="location.href = 'single-product.html';">
                        <div class="imageWrapper">
                            <img src="img/home/featured-collection/featured-collection-01.jpg" alt="feature-collection-image">
                            <div class="masking"><a href="product-grid-left-sidebar.html" class="btn viewBtn">View Prodocts</a></div>
                        </div>
                        <div class="caption">
                            <h4>Shoes</h4>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-xs-12">
                    <div class="thumbnail" onclick="location.href = 'single-product.html';">
                        <div class="imageWrapper">
                            <img src="img/home/featured-collection/featured-collection-02.jpg" alt="feature-collection-image">
                            <div class="masking"><a href="product-grid-left-sidebar.html" class="btn viewBtn">View Prodocts</a></div>
                        </div>
                        <div class="caption">
                            <h4>Bags</h4>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-xs-12">
                    <div class="thumbnail" onclick="location.href = 'single-product.html';">
                        <div class="imageWrapper">
                            <img src="img/home/featured-collection/featured-collection-03.jpg" alt="feature-collection-image">
                            <div class="masking"><a href="product-grid-left-sidebar.html" class="btn viewBtn">View Prodocts</a></div>
                        </div>
                        <div class="caption">
                            <h4>Glasses</h4>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row featuredProducts margin-bottom">
                <div class="col-xs-12">
                    <div class="page-header">
                        <h4>Featured Products</h4>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="owl-carousel featuredProductsSlider">
                        <div class="slide">
                            <div class="productImage clearfix">
                                <img src="img/home/featured-product/product-01.jpg" alt="featured-product-img">
                                <div class="productMasking">
                                    <ul class="list-inline btn-group" role="group">
                                        <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                                        <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                                        <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-eye"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="productCaption clearfix">
                                <a href="single-product.html">
                                    <h5>Mauris efficitur</h5>
                                </a>
                                <h3>$199</h3>
                            </div>
                        </div>
                        <div class="slide">
                            <div class="productImage">
                                <img src="img/home/featured-product/product-02.jpg" alt="featured-product-img">
                                <div class="productMasking">
                                    <ul class="list-inline btn-group" role="group">
                                        <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                                        <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                                        <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-eye"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="productCaption">
                                <a href="single-product.html">
                                    <h5>Nulla facilisi</h5>
                                </a>
                                <h3>$149</h3>
                            </div>
                        </div>
                        <div class="slide">
                            <div class="productImage">
                                <img src="img/home/featured-product/product-03.jpg" alt="featured-product-img">
                                <div class="productMasking">
                                    <ul class="list-inline btn-group" role="group">
                                        <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                                        <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                                        <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-eye"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="productCaption">
                                <a href="single-product.html">
                                    <h5>Praesent dui felis</h5>
                                </a>
                                <h3>$79</h3>
                            </div>
                        </div>
                        <div class="slide">
                            <div class="productImage">
                                <img src="img/home/featured-product/product-04.jpg" alt="featured-product-img">
                                <div class="productMasking">
                                    <ul class="list-inline btn-group" role="group">
                                        <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                                        <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                                        <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-eye"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="productCaption">
                                <a href="single-product.html">
                                    <h5>Cras eu faucibus</h5>
                                </a>
                                <h3>$109</h3>
                            </div>
                        </div>
                        <div class="slide">
                            <div class="productImage">
                                <img src="img/home/featured-product/product-05.jpg" alt="featured-product-img">
                                <div class="productMasking">
                                    <ul class="list-inline btn-group" role="group">
                                        <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                                        <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                                        <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-eye"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="productCaption">
                                <a href="single-product.html">
                                    <h5>Mauris lobortis augue</h5>
                                </a>
                                <h3>$199</h3>
                            </div>
                        </div>
                        <div class="slide">
                            <div class="productImage">
                                <img src="img/home/featured-product/product-06.jpg" alt="featured-product-img">
                                <div class="productMasking">
                                    <ul class="list-inline btn-group" role="group">
                                        <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                                        <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                                        <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-eye"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="productCaption">
                                <a href="single-product.html">
                                    <h5>Suspendisse suscipit</h5>
                                </a>
                                <h3>$149</h3>
                            </div>
                        </div>
                        <div class="slide">
                            <div class="productImage">
                                <img src="img/home/featured-product/product-07.jpg" alt="featured-product-img">
                                <div class="productMasking">
                                    <ul class="list-inline btn-group" role="group">
                                        <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                                        <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                                        <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-eye"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="productCaption">
                                <a href="single-product.html">
                                    <h5>Praesent a augue</h5>
                                </a>
                                <h3>$79</h3>
                            </div>
                        </div>
                        <div class="slide">
                            <div class="productImage">
                                <img src="img/home/featured-product/product-09.jpg" alt="featured-product-img">
                                <div class="productMasking">
                                    <ul class="list-inline btn-group" role="group">
                                        <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                                        <li><a href="cart-page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                                        <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-eye"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="productCaption">
                                <a href="single-product.html">
                                    <h5>Cras vel augue</h5>
                                </a>
                                <h3>$109</h3>
                            </div>
                        </div>
                    </div>
                </div>  
            </div>
            <div class="row latestArticles">
                <div class="col-xs-12">
                    <div class="page-header">
                        <h4>Latest Articles</h4>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-12">
                    <div class="thumbnail">
                        <h5><a href="blog-single-right-sidebar.html">Donec egestas tortor quis mattis</a></h5>
                        <span class="meta">July 16, 2016 by <a href="#">Abdus</a></span>
                        <a href="blog-single-right-sidebar.html"><img src="img/home/articles/articles-01.jpg" alt="article-image"></a>
                        <div class="caption">
                            <p>Nulla facilisi. Mauris efficitur, massa et iaculis accumsan, mauris velit ultrices purus, quis condimentum nibh dolor ut tortor.</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-12">
                    <div class="thumbnail">
                        <h5><a href="blog-single-right-sidebar.html">Pellentesque risus quis tellus</a></h5>
                        <span class="meta">July 16, 2016 by <a href="#">Abdus</a></span>
                        <a href="blog-single-right-sidebar.html"><img src="img/home/articles/articles-02.jpg" alt="article-image"></a>
                        <div class="caption">
                            <p>Praesent dui felis, gravida a auctor at, facilisis commodo ipsum. Cras eu faucibus justo. Nullam varius cursus nisi.</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-12">
                    <div class="thumbnail">
                        <h5><a href="blog-single-right-sidebar.html">Mauris lobortis augue ex</a></h5>
                        <span class="meta">July 16, 2016 by <a href="#">Abdus</a></span>
                        <a href="blog-single-right-sidebar.html"><img src="img/home/articles/articles-03.jpg" alt="article-image"></a>
                        <div class="caption">
                            <p>Etiam aliquam turpis quis blandit finibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-12">
                    <div class="thumbnail">
                        <h5><a href="blog-single-right-sidebar.html">Suspendisse vestibulum dignissim</a></h5>
                        <span class="meta">July 16, 2016 by <a href="#">Abdus</a></span>
                        <a href="blog-single-right-sidebar.html"><img src="img/home/articles/articles-04.jpg" alt="article-image"></a>
                        <div class="caption">
                            <p>Suspendisse tristique interdum est, at hendrerit nunc laoreet et. Nulla vel arcu ac turpis pulvinar tincidunt eu eu nisi.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>




</div>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="owl-carousel partnersLogoSlider">
                    <div class="slide">
                        <div class="partnersLogo clearfix">
                            <img src="img/home/partners/partner-01.png" alt="partner-img">
                        </div>
                    </div>  
                    <div class="slide">
                        <div class="partnersLogo clearfix">
                            <img src="img/home/partners/partner-02.png" alt="partner-img">
                        </div>
                    </div>
                    <div class="slide">
                        <div class="partnersLogo clearfix">
                            <img src="img/home/partners/partner-03.png" alt="partner-img">
                        </div>
                    </div>
                    <div class="slide">
                        <div class="partnersLogo clearfix">
                            <img src="img/home/partners/partner-04.png" alt="partner-img">
                        </div>
                    </div>
                    <div class="slide">
                        <div class="partnersLogo clearfix">
                            <img src="img/home/partners/partner-05.png" alt="partner-img">
                        </div>
                    </div>
                    <div class="slide">
                        <div class="partnersLogo clearfix">
                            <img src="img/home/partners/partner-01.png" alt="partner-img">
                        </div>
                    </div>  
                    <div class="slide">
                        <div class="partnersLogo clearfix">
                            <img src="img/home/partners/partner-02.png" alt="partner-img">
                        </div>
                    </div>
                    <div class="slide">
                        <div class="partnersLogo clearfix">
                            <img src="img/home/partners/partner-03.png" alt="partner-img">
                        </div>
                    </div>
                </div>              
            </div>
        </div>
    </div>
</section>
<!-- FOOTER -->
<div class="footer clearfix">
    <div class="container">
        <div class="row">
            <div class="col-sm-2 col-xs-12">
                <div class="footerLink">
                    <h5>Accessories</h5>
                    <ul class="list-unstyled">
                        <li><a href="#">Body care </a></li>
                        <li><a href="#">Chambray </a></li>
                        <li><a href="#">Floral </a></li>
                        <li><a href="#">Rejuvination </a></li>
                        <li><a href="#">Shaving </a></li>
                        <li><a href="#">Toilette </a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-2 col-xs-12">
                <div class="footerLink">
                    <h5>BRANDS</h5>
                    <ul class="list-unstyled">
                        <li><a href="#">Barbour </a></li>
                        <li><a href="#">Brioni </a></li>
                        <li><a href="#">Oliver Spencer</a></li>
                        <li><a href="#">Belstaff</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-2 col-xs-12">
                <div class="footerLink">
                    <h5>Accessories</h5>
                    <ul class="list-unstyled">
                        <li><a href="#">Body care </a></li>
                        <li><a href="#">Chambray </a></li>
                        <li><a href="#">Floral </a></li>
                        <li><a href="#">Rejuvination </a></li>
                        <li><a href="#">Shaving </a></li>
                        <li><a href="#">Toilette </a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-2 col-xs-12">
                <div class="footerLink">
                    <h5>Get in Touch</h5>
                    <ul class="list-unstyled">
                        <li>Call us at (555)-555-5555</li>
                        <li><a href="mailto:support@iamabdus.com">support@iamabdus.com</a></li>
                    </ul>
                    <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                        <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
                        <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-4 col-xs-12">
                <div class="newsletter clearfix">
                    <h4>Newsletter</h4>
                    <h3>Sign up now</h3>
                    <p>Enter your email address and get notified about new products. We hate spam!</p>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="your email address" aria-describedby="basic-addon2">
                        <a href="#" class="input-group-addon" id="basic-addon2">go <i class="glyphicon glyphicon-chevron-right"></i></a>
                    </div>
                </div>  
            </div>
        </div>
    </div>
</div>

<!-- COPY RIGHT -->
<div class="copyRight clearfix">
    <div class="container">
        <div class="row">
            <div class="col-sm-7 col-xs-12">
                <p>&copy; 2016 Copyright Bigbag Store Bootstrap Template by <a target="_blank" href="http://www.iamabdus.com/">Abdus</a>.</p>
            </div>
            <div class="col-sm-5 col-xs-12">
                <ul class="list-inline">
                    <li><img src="img/home/footer/card1.png"></li>
                    <li><img src="img/home/footer/card2.png"></li>
                    <li><img src="img/home/footer/card3.png"></li>
                    <li><img src="img/home/footer/card4.png"></li>
                </ul> 
            </div>
        </div>
    </div>
</div>